const nome = prompt("Qual é o seu nome?")
const comida1 = prompt("Qual a sua primeira comida favorita?")
const comida2 = prompt("Qual sua segunda comida favorita?")
const comida3 = prompt("Qual sua terceira comida favorita?")
console.log(`Estas são as comidas favoritas de ${nome} \n-${comida1}\n-${comida2}\n-${comida3}`)